apiVersion: v1
kind: Service
metadata:
  name: interaction-service
spec:
  selector:
    app: interaction-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: LoadBalancer
