apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-interaction-service
  labels:
    app: interaction-service
spec:
  secretStoreRef:
    name: interaction-service-secret-store
    kind: SecretStore
  target:
    name: interaction-service-external-secret
  data:
    - secretKey: DATABASE_HOST
      remoteRef:
        key: 'nodejs-microservices-interaction'
        property: DATABASE_HOST
    - secretKey: DATABASE_PORT
      remoteRef:
        key: 'nodejs-microservices-interaction'
        property: DATABASE_PORT
    - secretKey: DATABASE_USERNAME
      remoteRef:
        key: 'nodejs-microservices-interaction'
        property: DATABASE_USERNAME
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: 'nodejs-microservices-interaction'
        property: DATABASE_PASSWORD
    - secretKey: DATABASE_NAME
      remoteRef:
        key: 'nodejs-microservices-interaction'
        property: DATABASE_NAME
