//review
export const CREATE_REVIEW_FACTORY = 'CREATE_REVIEW_FACTORY';

//like
export const CREATE_LIKE_FACTORY = 'CREATE_LIKE_FACTORY';
export const DELETE_LIKE_FACTORY = 'DELETE_LIKE_FACTORY';

//comment
export const CREATE_COMMENT_FACTORY = 'CREATE_COMMENT_FACTORY';
export const DELETE_COMMENT_FACTORY = 'DELETE_COMMENT_FACTORY';
